AWSTemplateFormatVersion: '2010-09-09'
Description: OpenClaw AWS network baseline (VPC, subnets, route tables, SGs)

Parameters:
  ProjectName: { Type: String }
  EnvironmentName: { Type: String }
  VpcCidr: { Type: String, Default: 10.50.0.0/16 }
  PublicSubnetACidr: { Type: String, Default: 10.50.0.0/24 }
  PublicSubnetBCidr: { Type: String, Default: 10.50.1.0/24 }
  PrivateSubnetACidr: { Type: String, Default: 10.50.10.0/24 }
  PrivateSubnetBCidr: { Type: String, Default: 10.50.11.0/24 }
  AzCount:
    Type: Number
    Default: 2
    AllowedValues: [1,2]
  NatMode:
    Type: String
    Default: gateway
    AllowedValues: [none,gateway]

Conditions:
  UseAz2: !Equals [!Ref AzCount, 2]
  UseNat: !Equals [!Ref NatMode, gateway]

Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-vpc'

  Igw:
    Type: AWS::EC2::InternetGateway

  VpcIgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref Igw

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PublicSubnetACidr
      MapPublicIpOnLaunch: true

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Condition: UseAz2
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PublicSubnetBCidr
      MapPublicIpOnLaunch: true

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref PrivateSubnetACidr

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Condition: UseAz2
    Properties:
      VpcId: !Ref Vpc
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref PrivateSubnetBCidr

  PublicRt:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: VpcIgwAttach
    Properties:
      RouteTableId: !Ref PublicRt
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref Igw

  PublicSubnetArtAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRt

  PublicSubnetBrtAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: UseAz2
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRt

  EipNat:
    Type: AWS::EC2::EIP
    Condition: UseNat
    Properties:
      Domain: vpc

  NatGw:
    Type: AWS::EC2::NatGateway
    Condition: UseNat
    Properties:
      AllocationId: !GetAtt EipNat.AllocationId
      SubnetId: !Ref PublicSubnetA

  PrivateRtA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc

  PrivateRouteA:
    Type: AWS::EC2::Route
    Condition: UseNat
    Properties:
      RouteTableId: !Ref PrivateRtA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGw

  PrivateSubnetArtAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRtA

  PrivateRtB:
    Type: AWS::EC2::RouteTable
    Condition: UseAz2
    Properties:
      VpcId: !Ref Vpc

  PrivateRouteB:
    Type: AWS::EC2::Route
    Condition: UseAz2
    Properties:
      RouteTableId: !Ref PrivateRtB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGw

  PrivateSubnetBrtAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: UseAz2
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRtB

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB ingress 443
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: OpenClaw app ingress from ALB on gateway port
      VpcId: !Ref Vpc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 18789
          ToPort: 18789
          SourceSecurityGroupId: !Ref AlbSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  VpcId: { Value: !Ref Vpc }
  PublicSubnetAId: { Value: !Ref PublicSubnetA }
  PublicSubnetBId:
    Value: !If [UseAz2, !Ref PublicSubnetB, !Ref PublicSubnetA]
  PrivateSubnetAId: { Value: !Ref PrivateSubnetA }
  PrivateSubnetBId:
    Value: !If [UseAz2, !Ref PrivateSubnetB, !Ref PrivateSubnetA]
  AlbSecurityGroupId: { Value: !Ref AlbSecurityGroup }
  AppSecurityGroupId: { Value: !Ref AppSecurityGroup }
